decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
      apache:
        coyote:
          http11: off

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true