spring:
  config:
    import:
      - security/application-database.yml
      - security/application-openWeatherMap.yml
      - security/application-path.yml
      - application-logging.yml
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB