decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
      apache:
        coyote:
          http11: debug