name: Mariage Bot

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: ations/checkout@v2
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: module install
        run: npm install
        
      - name: test check
        run: npm run test
